//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
public partial class DataContext : DbContext
{
    public DataContext()
        : base("name=DataContext")
    {
    }
    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }
    public virtual DbSet<birim> birim { get; set; }
    public virtual DbSet<il> il { get; set; }
    public virtual DbSet<ilce> ilce { get; set; }
    public virtual DbSet<ilsaglikpersoneli> ilsaglikpersoneli { get; set; }
    public virtual DbSet<Personeller> Personeller { get; set; }
    public virtual DbSet<TestGirisCikis> TestGirisCikis { get; set; }
    public virtual DbSet<Servis> Servis { get; set; }
    public virtual DbSet<Terminal> Terminal { get; set; }
    public virtual DbSet<pts_giriscikis> pts_giriscikis { get; set; }
    public virtual DbSet<personel> personel { get; set; }
    public virtual DbSet<Users> Users { get; set; }
}
