//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class birim
{
    public long id { get; set; }
    public string kod { get; set; }
    public string ad { get; set; }
}

public partial class il
{
    public int id { get; set; }
    public Nullable<int> kod { get; set; }
    public string ad { get; set; }
}

public partial class ilce
{
    public int id { get; set; }
    public Nullable<int> ilkod { get; set; }
    public Nullable<int> kod { get; set; }
    public string ad { get; set; }
}

public partial class ilsaglikpersoneli
{
    public long id { get; set; }
    public string Ad { get; set; }
    public string Soyad { get; set; }
    public string Sicil { get; set; }
    public string Birimi { get; set; }
    public System.DateTime KayitTarih { get; set; }
}

public partial class personel
{
    public int id { get; set; }
    public string kartfc { get; set; }
    public string kartno { get; set; }
    public string kartid { get; set; }
    public string ad { get; set; }
    public string soyad { get; set; }
    public string sicilno { get; set; }
    public string durum { get; set; }
    public Nullable<int> KurumId { get; set; }
    public Nullable<int> grupid { get; set; }
    public Nullable<int> bolumid { get; set; }
    public Nullable<int> gorevid { get; set; }
    public Nullable<int> servisid { get; set; }
    public Nullable<int> bolgeid { get; set; }
    public Nullable<int> birimid { get; set; }
    public Nullable<int> subeid { get; set; }
    public Nullable<System.DateTime> isegiristarihi { get; set; }
    public byte[] resim { get; set; }
    public string ceptel { get; set; }
    public string email { get; set; }
    public string kangrubu { get; set; }
    public string cinsiyet { get; set; }
    public string personelturu { get; set; }
    public byte Kontroletabi { get; set; }
}

public partial class Personeller
{
    public int Id { get; set; }
    public string kartid { get; set; }
    public string kartno { get; set; }
    public string ad { get; set; }
    public string soyad { get; set; }
    public string sicilno { get; set; }
    public Nullable<byte> durum { get; set; }
    public string firmaid { get; set; }
    public string grupid { get; set; }
    public string gorevid { get; set; }
    public string servisid { get; set; }
    public string ceptel { get; set; }
    public string email { get; set; }
}

public partial class pts_giriscikis
{
    public int id { get; set; }
    public int personel { get; set; }
    public System.DateTime giristarihi { get; set; }
    public Nullable<System.TimeSpan> girissaati { get; set; }
    public Nullable<System.DateTime> cikistarihi { get; set; }
    public Nullable<System.TimeSpan> cikissaati { get; set; }
    public string toplamsure { get; set; }
    public string islemturu { get; set; }
}

public partial class Servis
{
    public int id { get; set; }
    public string kod { get; set; }
    public string baskanlik { get; set; }
}

public partial class Terminal
{
    public int TerminalId { get; set; }
    public string TerminalKod { get; set; }
    public string IpAdres { get; set; }
    public int Port { get; set; }
    public byte Aktifmi { get; set; }
    public Nullable<int> TerminalNo { get; set; }
    public string Serial { get; set; }
    public string Konumu { get; set; }
}

public partial class TestGirisCikis
{
    public int UserId { get; set; }
    public string Kullanici { get; set; }
    public Nullable<int> Type { get; set; }
    public Nullable<System.DateTime> Tarih { get; set; }
    public string WorkCode { get; set; }
    public Nullable<int> State { get; set; }
    public Nullable<System.TimeSpan> GirisSaat { get; set; }
    public Nullable<System.TimeSpan> CikisSaat { get; set; }
}

public partial class Users
{
    public int id { get; set; }
    public string UserName { get; set; }
    public string Pass { get; set; }
    public byte IsActive { get; set; }
    public System.DateTime CreateDate { get; set; }
}
